config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "rooms#index"
  
  scope "(:locale)" do

    scope module: :users do
      resources :users, only: [:edit, :update]
    end

    resources :rooms, only:[:new,:create,:index,:destroy] do
      resources :messages, only:[:create,:index,:new]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord

  validates :content, presence: true, unless: :was_attached?
  def was_attached?
    self.image.attached?
  end

  belongs_to :user
  has_one_attached :image
  belongs_to :room

end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_many :messages, dependent: :destroy

  validates :title, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/tran.rb
class Tran < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  with_options presence: true do
    validates :name
    validates :post
    validates :email, uniqueness: true, length: { minimum: 6 }

    # template = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
    # validates :password, format: { with: template }

  end

  has_many :messages
  has_many :room_users
  has_many :rooms, through: :room_users

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller? 
  before_action :authenticate_user! 

  protect_from_forgery with: :exception
  before_action :set_locale


  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys: [ :name,:email,:password,:post])
  end

  def set_locale #パスのパラメータを現在の言語I18n.localeに設定
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {}) #デフォルト値として現在の言語を指定
     { :locale => I18n.locale }.merge options
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # before_action :message_params, only: [:index,:create]
  before_action :message_trans, only: [:create]


  def index
    @message = Message.new
    @room = Room.find(params[:room_id])
    @messages = @room.messages.includes(:user)
  end

  def create
    if @message.save
      redirect_to room_messages_path(@room)
    else
      @messages = @room.messages.includes(:user)
      render :index
    end
  end



  def move_to_index
    unless user_signed_in
      redirect_to action: :index
    end 
  end

  private
  def message_params
    params.require(:message).permit(:content,:image).merge(user_id: current_user.id)
  end

  def message_trans
    client = Aws::Translate::Client.new(region: 'us-west-2')
    @room = Room.find(params[:room_id])
    @message = @room.messages.create(message_params)

    if params[:language_id] == "1"
      result = client.translate_text(text: @message.content, source_language_code: "auto", target_language_code: "ja")
    elsif params[:language_id] == "2"
      result = client.translate_text(text: @message.content, source_language_code: "auto", target_language_code: "en")
    elsif params[:language_id] == "3"
      result = client.translate_text(text: @message.content, source_language_code: "auto", target_language_code: "zh")
    else params[:language] == "0"
      return
    end
    @message.comment = result.translated_text
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    # @room = Room.find(params[:room_id])
    @rooms = Room.all.order(id:'DESC')
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end

  private

  def room_params
    params.require(:room).permit(:title, user_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:email,:post)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ProtoSpace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="5-6.css">

  </head>

  <body>
    <div id="particles-js"></div>
      <div id="wrapper">
        <header class="header">
          <div class="inner">
            <div class="nav">
              <div class="nav__left">
                <%= link_to image_tag("logo.jpg", class: :logo), root_path %>
              </div>
              <div class="nav_center">
                <nav>
                  <ul>
                    <li>
                      <div class="nav_center_top">
                        <div class="nav_center_ja">
                          <div class="nav_image" >
                            <%= link_to('日本語',{:locale => 'ja'} ,{class: 'nav_letter'}) %>
                          </div>
                        </div>
                        <div class="nav_center_en">
                          <div class="nav_image" >
                            <%= link_to('English',{:locale => 'en'} ,{class: 'nav_letter'}) %>
                          </div>
                        </div>
                        <div class="nav_center_ch">
                          <div class="nav_image" >
                            <%= link_to('中国語',{:locale => 'zh_CN'} ,{class: 'nav_letter'}) %>
                          </div>
                        </div>
                      </div>
                    </li>
                  </ul>
                </nav>
              </div>
              <div class="nav_right">
                <div class="nav_right_sub">
                  <% if user_signed_in? %>
                      <%= link_to t('application.application.log_out'), destroy_user_session_path, method: :delete,class: :nav__logout %>
                      <%= link_to t('application.application.chat_room'),new_room_path, method: :get, class: :nav__btn %>
                      <div class=nav_right_current_user>
                        <%= t('application.application.log_in')%><%= "："%>
                        <%= link_to current_user.name, class:'nav_right_user' %>
                      </div>                  
                  <% else %>
                      <%= link_to t('application.application.log_in') ,new_user_session_path, class: :nav__btn %>
                      <%= link_to t('application.application.sign_up') , new_user_registration_path, class: :nav__btn %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </header>
        <%= yield %>
        <%# <footer class="footer">
          <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
        </footer> %>
      <!--/wrapper--></div>
    <script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
    <script src="http://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/move02/5-8/js/5-8.js"></script>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class ="main_bar_top">
  <div class="main_bar_top_left">
    <div class="main_title">
      <%=  link_to t('application.application.subject') %><%= " : " %>
      <%=@room.title%>
    </div>
  </div>
  <div class="main_bar_top_right">
    <div class="chat-btn-form">
      <%= link_to t('application.application.back_to_the_list'), rooms_path,class:"chat-btn" %>
      <%= link_to t('application.application.finish_a_chat'), room_path(@room) ,method: :delete, class:"chat-btn" %>
    </div>
  </div>
</div>

<%= form_with model: [@room, @message], class: 'form', local: true do |f| %>
  <div class="form-input">
    <%= f.text_field :content, class: 'form-message', placeholder: "#{t('application.application.type')}" %>
    <%= f.file_field :image, class: "form_image" %>
  </div>
  <div class="selectbox">
    <select name=language_id id=language_id >
      <option value="0">言語選択 </option>
      <option value="1">日本語</option>
      <option value="2">英語  </option>
      <option value="3">中国語</option>
    </select>
  </div>


  <%# <label class="form-image"> %>
    <%# <span class="image-file"><%= link_to t('application.application.image')</span> %>
    <%# <%= f.file_field :image, class: "form_image" %> 
  <%# </label> %>

  <%= f.submit "#{t('application.application.send')}", class: 'form-submit' %>
<% end %>


<div class="main_bar_middle">
    <%= render partial: 'message', collection: @messages %>
</div>

app/views/messages/_message.html.erb
<div class="main_bar_middle_top">
    <div class = "main-left_time">
      <div class="message-date">
        <!-- 投稿した時刻を出力する -->
        <%= l message.created_at %>
      </div>
      <div class="message-user">
        <!-- 投稿したユーザー名情報を出力する -->
        <%= message.user.name %>
      </div>
    </div>
    <div class="message-upper">

    </div>
    <div class="message">
      <div class="message-content">
        <!-- 投稿したメッセージ内容を記述する -->
        <%= message.content %><br />
        <%=link_to " (#{t('application.application.translation')}) "%><%= message.comment %>
      </div>
      <%= image_tag message.image.variant(resize: '200x200'), class: 'message-image' if message.image.attached? %>
    </div>

</div>

app/views/messages/_side_bar.html.erb
<div class="side_bar_top">
</div>

<div class="side_bar_down">
  <div class="chat-room">
   
    <div class="chat-room_sub_left">
      <div class="chat-room-sub_top_left">
        <%= link_to t('application.application.post')%>
      </div>
      <div class="chat-room_sub_left_post">
        <% @room.users.each do |user| %>
          <div class="chat-room_sub_left_post">
            <%= user.name %>
          </div>
        <% end %>       
      </div>
    </div>

    <div class="chat-room_sub_right">
      <div class="chat-room-sub_top_right">    
        <%=link_to t('application.application.name')%>
      </div>
      <div class="chat-room_sub_right_post">      
        <% @room.users.each do |user| %>
          <div class="chat-room_sub_right_post">
            <%= user.post%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div> 

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="side_bar">
     <%= render "side_bar" %>

  </div>
  <div class="chat">
    <%= render "main_chat" %>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="rooms-index">
  <div class="rooms-index-middle">
    <div class="rooms-index-middle_list">
      <%= link_to t('application.application.chat_room_list')%>
    </h3>
  </div>
  <div class="room-index-lower">
    <% @rooms.each do |room| %>
      <div class="room-index-lower_box">
        <%= link_to room_messages_path(room) do%>
          <div class="room-index-lower_room">

            <div class="room-info">
              <%= "件名：" "#{room.title}" %>
            </div>
          </div>
        <%end%>
      </div>
      <div class="room-index-lower_space">
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/new.html.erb
<div calss='chat-room-form'>
  <div class='chat-room-form_top'>
    <h1><%= link_to t('application.application.chat_room')%></h1>
    <div class='chat-room-back'>
    <%= form_with model: @room, local: true do |f| %>
    
      <%= render 'devise/shared/error_messages', model: f.object %>

      <div class='chat-room-form_field'>
        <div class='chat-room-label_field'>
          <%= link_to t('application.application.room_name') %>
        </div>
        <div class='chat-room-name'>
          <%= f.text_field :title, class: 'chat-room-name_fill', placeholder:"#{t('application.application.fill_in')}"%>
        </div> 
      </div>

      <div class='chat-room-center'>
        <div class ='chat-room-center_select'>
          <div class='chat-room-center_select_post'>
            <%= link_to t('application.application.post')%>
          </div>
          <div class='chat-room-center_select_post'>        
            <%= link_to t('application.application.email')%>
          </div>
        </div>
        <div class = 'chat-room-center_fill'>
          <div id="input_pluralBox">
            <div id="input_plural">
              <input type="button" value="＋" class="add pluralBtn">
              <input type="button" value="－" class="del pluralBtn">

              <select post="room[user_ids][]" class='room-user-select'>
                <%# <div class="room-user-select"> %>
                  <option value=""><%=link_to t('application.application.select_post')%></option>
                  <% User.where.not(id: current_user.id).each do |user| %>
                    <option value=<% user.id%>%><%= user.post%></option>
                  <% end %>
                <%# </div> %>
              </select>
              <select name="room[user_ids][]" class='room-user-select'>
                <option value=""><%=link_to t('application.application.select_name')%></option>
                <% User.where.not(id: current_user.id).each do |user| %>
                  <option value=<%= user.id %>><%= user.name %></option>
                <% end %>
              </select>

              <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
              <script type="text/javascript">
                $(document).on("click", ".add", function() {
                $(this).parent().clone(true).insertAfter($(this).parent());
                });
                $(document).on("click", ".del", function() {
                var target = $(this).parent();
                if (target.parent().children().length > 1) {
                target.remove();
                    }
                });
              </script>
            </div>
            <input name="room[user_ids][]" type="hidden" value=<%= current_user.id%>>
          </div>
        </div>
        <div class = 'chat-room_action_btn_form'>
          <%= f.submit "#{t('application.application.create')}",class: 'chat-room-action_btn'%>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class="field">
            <%= f.label :email, "メールアドレス"%><br />
            <%= f.email_field :email, id:"user_email", autofocus: true, autocomplete: "email" %>
          </div>

          <div class="field">
            <%= f.label :name, "名前"%><br />
            <%= f.text_field :name, id:"user_name"%>
          </div>

          <div class="field">
            <%= f.label :post, "部署" %><br />
            <%= f.text_field :post, class: :form__text, id:"user_post" %>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>